# -*- coding: utf-8 -*-
"""9.20_nongsan_first.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GErVHB_nK2l0vtmDIr5Fq1LNznMfXjYu
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv]
!rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic') 
import tensorflow as tf
import keras
from numpy import array
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
import numpy as np
import math
import matplotlib as mpl
from IPython.core.display import display, HTML
from datetime import datetime
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from sklearn.preprocessing import MinMaxScaler, RobustScaler
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.svm import SVR
from scipy.stats import expon, reciprocal
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_squared_log_error
from tensorflow.keras import Sequential
from tensorflow.keras import layers
from keras.models import load_model
from tensorflow.keras.layers import Dense, LSTM
from random import *
from sklearn.ensemble import RandomForestRegressor
import seaborn as sns
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)
pd.set_option('max_rows', 300)
pd.options.display.float_format = '{:.3f}'.format
import gc

drive.mount('/content/gdrive')

df = pd.read_csv('/content/gdrive/MyDrive/data/농산물/public/train.csv', encoding='utf-8')
df.head()

df[:100]

feature = df.columns[2:]
feature

feature_price = []
for i in range(1,22):
  feature_price.append(feature[2*i-1])

df[feature_price[10:]].plot(figsize=(20,10))

df[feature_price[5:]].plot(figsize=(20,10))

fig = plt.figure(dpi=200)
plt.xticks(rotation=90)
sns.boxplot(data=df[feature_price[10:19]])